# Site settings
title: Rupert Deese
header-img: img/home-bg.jpg
email: hartdeese@mac.com
description: "Friendship"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: rupehart
github_username: rdeese 
facebook_username: cityislander 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
